# Generated by Django 4.2 on 2023-06-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_complete_task_created_task_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('usn', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=30)),
                ('branch', models.CharField(max_length=20)),
            ],
        ),
    ]
